source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LFramework_Example', :exclusive => true do
  pod "LFramework", :path => "../"
  pod "LFramework/LClient", :path => "../"
end

target 'LFramework_Tests', :exclusive => true do
  pod "LFramework", :path => "../"
  pod "LFramework/LClient", :path => "../"

# pod 'Quick', '~> 0.8.0'
# pod 'Nimble', '3.0.0'
  pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end